export default {
  ADD_TO_CART_START: 'cart/ADD_TO_CART_START',
  ADD_TO_CART_SUCCESS: 'cart/ADD_TO_CART_SUCCESS',
  ADD_TO_CART_FAILURE: 'cart/ADD_TO_CART_FAILURE',

  REMOVE_FROM_CART_START: 'cart/REMOVE_FROM_CART_START',
  REMOVE_FROM_CART_SUCCESS: 'cart/REMOVE_FROM_CART_SUCCESS',
  REMOVE_FROM_CART_FAILURE: 'cart/REMOVE_FROM_CART_FAILURE',

  CLEAR_CART_START: 'cart/CLEAR_CART_START',
  CLEAR_CART_SUCCESS: 'cart/CLEAR_CART_SUCCESS',
  CLEAR_CART_FAILURE: 'cart/CLEAR_CART_FAILURE',
};
