export default {
  GET_ALL_PRODUCTS_START: 'products/GET_ALL_PRODUCTS_START',
  GET_ALL_PRODUCTS_SUCCESS: 'products/GET_ALL_PRODUCTS_SUCCESS',
  GET_ALL_PRODUCTS_FAILURE: 'products/GET_ALL_PRODUCTS_FAILURE',

  GET_USER_PRODUCTS_START: 'products/GET_USER_PRODUCTS_START',
  GET_USER_PRODUCTS_SUCCESS: 'products/GET_USER_PRODUCTS_SUCCESS',
  GET_USER_PRODUCTS_FAILURE: 'products/GET_USER_PRODUCTS_FAILURE',

  GET_PRODUCT_START: 'products/GET_PRODUCT_START',
  GET_PRODUCT_SUCCESS: 'products/GET_PRODUCT_SUCCESS',
  GET_PRODUCT_FAILURE: 'products/GET_PRODUCT_FAILURE',

  CREATE_PRODUCT_START: 'products/CREATE_PRODUCT_START',
  CREATE_PRODUCT_SUCCESS: 'products/CREATE_PRODUCT_SUCCESS',
  CREATE_PRODUCT_FAILURE: 'products/CREATE_PRODUCT_FAILURE',

  UPDATE_PRODUCT_START: 'products/UPDATE_PRODUCT_START',
  UPDATE_PRODUCT_SUCCESS: 'products/UPDATE_PRODUCT_SUCCESS',
  UPDATE_PRODUCT_FAILURE: 'products/UPDATE_PRODUCT_FAILURE',

  DELETE_PRODUCT_START: 'products/DELETE_PRODUCT_START',
  DELETE_PRODUCT_SUCCESS: 'products/DELETE_PRODUCT_SUCCESS',
  DELETE_PRODUCT_FAILURE: 'products/DELETE_PRODUCT_FAILURE',

  GET_PRODUCT_ORIGINS_START: 'products/GET_PRODUCT_ORIGINS_START',
  GET_PRODUCT_ORIGINS_SUCCESS: 'products/GET_PRODUCT_ORIGINS_SUCCESS',
  GET_PRODUCT_ORIGINS_FAILURE: 'products/GET_PRODUCT_ORIGINS_FAILURE',
};
